language: generic
matrix:
  include:
    - os: linux
      env: COMPILER_NAME=gcc CXX=g++-5 CC=gcc-5
      addons:
        apt:
          sources: &sources
            - llvm-toolchain-precise-3.8
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
            - libboost-python-dev
    - os: linux
      env: COMPILER_NAME=clang CXX=clang++-6.0 CC=clang-6.0
      addons:
        apt:
         sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-6.0
         packages:
            - clang-6.0
            - libstdc++-7-dev
            - libboost-python-dev
script:
    - cmake --version
    - mkdir -p build
    - cd build
    - cmake ..
    - make